### ISSUE TITLE
run.exe似乎已遗失

### ISSUE THREAD

**Issue by Bang0518** [PotatoChipsNinja/COVID-19-Travel-System#1]
```在 /binary 目录下包含了 Windows 平台 64 位可执行文件。```

**Comment by PotatoChipsNinja** [comment]
你好，win64 可执行文件可以在 [Releases](https://github.com/PotatoChipsNinja/COVID-19-Travel-System/releases) 中得到，其他架构可通过 `go build -o run.exe` 自行构建

**Comment by Bang0518** [comment]
谢谢学长！请问一下，如果要制作北邮校园地图导览的话，应该用什么解决方案比较合适呢？目前考虑使用高德API。

**Comment by PotatoChipsNinja** [comment]
> 谢谢学长！请问一下，如果要制作北邮校园地图导览的话，应该用什么解决方案比较合适呢？目前考虑使用高德API。

主流的地图 API 应该都可以满足需求
